---
- name: Mount drives
  file: path={{ mount_path }}/{{ item }} state=directory
    owner=root group=root
  with_items: {{ ansible_devices }}

- apt_repository: repo='deb http://www.greyhole.net/releases/deb stable main' state=present
- apt_key: url=http://www.greyhole.net/releases/deb/greyhole-debsig.asc state=present

- name: Install common packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - samba
    - greyhole
    - system-config-samba
    - cifs-utils
    - curl
    - python-mysqldb
    - python-apt

- name: Start MySQL service
  service: name=mysql state=started enabled=yes

- name: Create MySQL db
  mysql_db: name={{ db_name }} state=present

- name: Create MySQL user
  mysql_user: name={{ db_user }} password={{ db_pass }} state=present
    priv=greyhole.*:ALL

- name: Import MySQL db
  mysql_db: name={{ db_name }} login_user={{ db_user }} login_password={{ db_pass }}
    state=import target=/usr/share/greyhole/schema-mysql.sql
  ignore_errors: yes

- name: Copy greyhole.conf
  template: src=greyhole.conf.j2 dest=/etc/greyhole.conf
    owner=root group=root mode=0644
